# Generated by Django 2.1.7 on 2019-06-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='state',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
